[2024-11-01T22:19:52.069+0000] {processor.py:186} INFO - Started process (PID=982) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:19:52.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:19:52.072+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:19:52.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:19:52.076+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:19:52.073+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:19:52.077+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:19:52.097+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:20:22.246+0000] {processor.py:186} INFO - Started process (PID=997) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:22.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:22.249+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:22.248+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:22.251+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:22.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:22.251+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:22.271+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:20:24.268+0000] {processor.py:186} INFO - Started process (PID=1002) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:24.268+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:24.271+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:24.270+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:24.274+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:24.272+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:24.274+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:24.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.045 seconds
[2024-11-01T22:20:27.322+0000] {processor.py:186} INFO - Started process (PID=1007) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:27.322+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:27.324+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:27.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:27.326+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:27.325+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:27.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:27.348+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:20:29.355+0000] {processor.py:186} INFO - Started process (PID=1012) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:29.356+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:29.357+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:29.357+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:29.360+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:29.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:29.360+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:29.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:20:31.387+0000] {processor.py:186} INFO - Started process (PID=1017) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:31.387+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:31.390+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:31.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:31.392+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:31.391+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:31.392+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:31.413+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:20:32.419+0000] {processor.py:186} INFO - Started process (PID=1022) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:32.419+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:32.421+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:32.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:32.424+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:32.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:32.424+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:32.446+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:20:34.449+0000] {processor.py:186} INFO - Started process (PID=1027) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:34.450+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:34.453+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:34.453+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:34.455+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:34.455+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:34.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:34.475+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:20:36.688+0000] {processor.py:186} INFO - Started process (PID=1037) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:36.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:36.692+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:36.691+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:36.696+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:36.694+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:36.697+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:36.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.043 seconds
[2024-11-01T22:20:38.697+0000] {processor.py:186} INFO - Started process (PID=1049) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:38.697+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:38.699+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:38.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:38.701+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:38.700+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:38.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:38.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:20:40.709+0000] {processor.py:186} INFO - Started process (PID=1054) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:40.709+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:40.711+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:40.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:40.714+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:40.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:40.714+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:40.737+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.033 seconds
[2024-11-01T22:20:43.792+0000] {processor.py:186} INFO - Started process (PID=1059) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:43.793+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:43.796+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:43.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:43.799+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:43.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:43.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:43.825+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.039 seconds
[2024-11-01T22:20:44.860+0000] {processor.py:186} INFO - Started process (PID=1064) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:44.861+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:44.864+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:44.864+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:44.868+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:44.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:44.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:44.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.039 seconds
[2024-11-01T22:20:47.879+0000] {processor.py:186} INFO - Started process (PID=1069) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:47.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:47.882+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:47.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:47.885+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:47.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:47.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:47.915+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.043 seconds
[2024-11-01T22:20:49.959+0000] {processor.py:186} INFO - Started process (PID=1074) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:49.966+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:49.968+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:49.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:49.974+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:49.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:49.975+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:50.015+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.063 seconds
[2024-11-01T22:20:52.976+0000] {processor.py:186} INFO - Started process (PID=1079) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:52.977+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:52.979+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:52.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:52.981+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:52.980+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:52.981+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:53.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:20:57.000+0000] {processor.py:186} INFO - Started process (PID=1084) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:57.000+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:57.003+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:57.002+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:57.005+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:57.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:57.005+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:57.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.039 seconds
[2024-11-01T22:20:59.075+0000] {processor.py:186} INFO - Started process (PID=1089) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:59.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:20:59.079+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:59.079+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:59.083+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:20:59.081+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:20:59.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:20:59.113+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.045 seconds
[2024-11-01T22:21:01.108+0000] {processor.py:186} INFO - Started process (PID=1094) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:01.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:01.114+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:01.113+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:01.119+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:01.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:01.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:01.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.080 seconds
[2024-11-01T22:21:03.174+0000] {processor.py:186} INFO - Started process (PID=1099) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:03.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:03.176+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:03.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:03.179+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:03.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:03.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:03.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:21:07.217+0000] {processor.py:186} INFO - Started process (PID=1104) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:07.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:07.229+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:07.229+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:07.239+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:07.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:07.240+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:07.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.064 seconds
[2024-11-01T22:21:10.304+0000] {processor.py:186} INFO - Started process (PID=1120) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:10.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:10.307+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:10.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:10.309+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:10.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:10.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:10.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:21:21.399+0000] {processor.py:186} INFO - Started process (PID=1125) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:21.400+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:21.402+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:21.402+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:21.405+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:21.403+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG, 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:21.405+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:21.422+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:21:24.428+0000] {processor.py:186} INFO - Started process (PID=1130) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:24.429+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:24.431+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:24.431+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:24.433+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:24.432+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG, time
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:24.434+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:24.458+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.034 seconds
[2024-11-01T22:21:50.626+0000] {processor.py:186} INFO - Started process (PID=1147) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:50.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:50.629+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:50.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:50.632+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:50.631+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG, 
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:50.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:50.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.041 seconds
[2024-11-01T22:21:55.650+0000] {processor.py:186} INFO - Started process (PID=1152) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:55.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:55.652+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:55.652+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:55.655+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:55.654+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG, int
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:55.655+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:55.679+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.035 seconds
[2024-11-01T22:21:57.664+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:57.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:57.666+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:57.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:57.668+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:57.667+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG,
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:57.668+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:57.706+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.048 seconds
[2024-11-01T22:21:59.723+0000] {processor.py:186} INFO - Started process (PID=1162) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:59.724+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:21:59.726+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:59.726+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:59.734+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:21:59.733+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:21:59.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:21:59.794+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.078 seconds
[2024-11-01T22:22:29.959+0000] {processor.py:186} INFO - Started process (PID=1178) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:22:29.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:22:29.962+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:22:29.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:22:29.964+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:22:29.963+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:22:29.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:22:29.995+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.040 seconds
[2024-11-01T22:23:00.143+0000] {processor.py:186} INFO - Started process (PID=1195) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:23:00.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:23:00.147+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:23:00.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:23:00.150+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:23:00.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:23:00.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:23:00.170+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.033 seconds
[2024-11-01T22:23:30.327+0000] {processor.py:186} INFO - Started process (PID=1211) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:23:30.327+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:23:30.330+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:23:30.329+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:23:30.332+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:23:30.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:23:30.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:23:30.358+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.035 seconds
[2024-11-01T22:24:00.511+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:24:00.511+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:24:00.513+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:24:00.513+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:24:00.516+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:24:00.515+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:24:00.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:24:00.538+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:24:30.715+0000] {processor.py:186} INFO - Started process (PID=1244) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:24:30.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:24:30.719+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:24:30.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:24:30.722+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:24:30.720+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:24:30.723+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:24:30.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.055 seconds
[2024-11-01T22:25:00.933+0000] {processor.py:186} INFO - Started process (PID=1260) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:25:00.934+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:25:00.937+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:25:00.936+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:25:00.940+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:25:00.938+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:25:00.940+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:25:00.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.033 seconds
[2024-11-01T22:25:31.113+0000] {processor.py:186} INFO - Started process (PID=1276) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:25:31.114+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:25:31.115+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:25:31.115+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:25:31.117+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:25:31.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:25:31.118+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:25:31.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:26:01.305+0000] {processor.py:186} INFO - Started process (PID=1292) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:26:01.305+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:26:01.307+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:26:01.307+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:26:01.309+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:26:01.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:26:01.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:26:01.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:26:31.483+0000] {processor.py:186} INFO - Started process (PID=1307) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:26:31.484+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:26:31.486+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:26:31.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:26:31.488+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:26:31.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:26:31.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:26:31.509+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:27:01.662+0000] {processor.py:186} INFO - Started process (PID=1323) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:27:01.663+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:27:01.666+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:27:01.666+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:27:01.669+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:27:01.668+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:27:01.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:27:01.696+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.040 seconds
[2024-11-01T22:27:31.857+0000] {processor.py:186} INFO - Started process (PID=1338) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:27:31.858+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:27:31.860+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:27:31.859+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:27:31.862+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:27:31.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:27:31.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:27:31.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.033 seconds
[2024-11-01T22:28:02.038+0000] {processor.py:186} INFO - Started process (PID=1354) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:28:02.039+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:28:02.040+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:28:02.040+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:28:02.043+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:28:02.042+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:28:02.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:28:02.064+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:28:32.211+0000] {processor.py:186} INFO - Started process (PID=1371) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:28:32.212+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:28:32.213+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:28:32.213+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:28:32.215+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:28:32.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:28:32.216+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:28:32.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:29:02.397+0000] {processor.py:186} INFO - Started process (PID=1387) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:29:02.398+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:29:02.400+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:29:02.399+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:29:02.402+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:29:02.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:29:02.403+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:29:02.430+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.038 seconds
[2024-11-01T22:29:32.581+0000] {processor.py:186} INFO - Started process (PID=1403) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:29:32.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:29:32.583+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:29:32.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:29:32.585+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:29:32.584+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:29:32.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:29:32.611+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.035 seconds
[2024-11-01T22:30:02.787+0000] {processor.py:186} INFO - Started process (PID=1420) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:30:02.788+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:30:02.793+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:30:02.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:30:02.798+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:30:02.796+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:30:02.800+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:30:02.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.068 seconds
[2024-11-01T22:30:33.001+0000] {processor.py:186} INFO - Started process (PID=1436) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:30:33.002+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:30:33.005+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:30:33.004+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:30:33.008+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:30:33.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:30:33.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:30:33.038+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.043 seconds
[2024-11-01T22:31:03.193+0000] {processor.py:186} INFO - Started process (PID=1452) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:31:03.193+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:31:03.195+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:31:03.195+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:31:03.197+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:31:03.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:31:03.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:31:03.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:31:33.372+0000] {processor.py:186} INFO - Started process (PID=1468) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:31:33.373+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:31:33.375+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:31:33.375+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:31:33.377+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:31:33.376+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:31:33.377+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:31:33.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:32:03.574+0000] {processor.py:186} INFO - Started process (PID=1485) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:32:03.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:32:03.577+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:32:03.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:32:03.579+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:32:03.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:32:03.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:32:03.600+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:32:33.771+0000] {processor.py:186} INFO - Started process (PID=1501) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:32:33.772+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:32:33.774+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:32:33.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:32:33.776+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:32:33.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:32:33.776+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:32:33.795+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.028 seconds
[2024-11-01T22:33:03.958+0000] {processor.py:186} INFO - Started process (PID=1518) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:33:03.958+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:33:03.960+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:33:03.960+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:33:03.962+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:33:03.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:33:03.963+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:33:03.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.034 seconds
[2024-11-01T22:33:34.141+0000] {processor.py:186} INFO - Started process (PID=1534) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:33:34.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:33:34.144+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:33:34.143+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:33:34.146+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:33:34.145+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:33:34.146+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:33:34.167+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:34:04.316+0000] {processor.py:186} INFO - Started process (PID=1550) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:34:04.316+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:34:04.318+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:34:04.318+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:34:04.321+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:34:04.320+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:34:04.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:34:04.342+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:34:34.504+0000] {processor.py:186} INFO - Started process (PID=1567) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:34:34.504+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:34:34.507+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:34:34.506+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:34:34.509+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:34:34.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:34:34.510+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:34:34.532+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.033 seconds
[2024-11-01T22:35:04.705+0000] {processor.py:186} INFO - Started process (PID=1582) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:35:04.705+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:35:04.707+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:35:04.707+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:35:04.709+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:35:04.708+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:35:04.710+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:35:04.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:35:34.876+0000] {processor.py:186} INFO - Started process (PID=1598) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:35:34.877+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:35:34.879+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:35:34.878+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:35:34.881+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:35:34.880+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:35:34.881+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:35:34.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:36:05.051+0000] {processor.py:186} INFO - Started process (PID=1614) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:36:05.051+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:36:05.053+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:36:05.053+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:36:05.055+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:36:05.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:36:05.056+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:36:05.078+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:36:35.229+0000] {processor.py:186} INFO - Started process (PID=1630) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:36:35.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:36:35.232+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:36:35.231+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:36:35.234+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:36:35.233+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:36:35.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:36:35.254+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:37:05.414+0000] {processor.py:186} INFO - Started process (PID=1646) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:37:05.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:37:05.418+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:37:05.417+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:37:05.421+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:37:05.419+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:37:05.421+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:37:05.447+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.039 seconds
[2024-11-01T22:37:35.595+0000] {processor.py:186} INFO - Started process (PID=1662) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:37:35.595+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:37:35.597+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:37:35.597+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:37:35.600+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:37:35.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:37:35.600+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:37:35.620+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:38:05.765+0000] {processor.py:186} INFO - Started process (PID=1678) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:38:05.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:38:05.768+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:38:05.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:38:05.770+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:38:05.769+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:38:05.771+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:38:05.790+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:38:35.945+0000] {processor.py:186} INFO - Started process (PID=1694) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:38:35.946+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:38:35.948+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:38:35.948+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:38:35.950+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:38:35.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:38:35.950+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:38:35.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:39:06.123+0000] {processor.py:186} INFO - Started process (PID=1711) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:39:06.124+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:39:06.126+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:39:06.126+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:39:06.128+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:39:06.128+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:39:06.129+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:39:06.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:39:36.313+0000] {processor.py:186} INFO - Started process (PID=1727) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:39:36.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:39:36.315+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:39:36.315+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:39:36.317+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:39:36.317+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:39:36.318+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:39:36.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:40:06.511+0000] {processor.py:186} INFO - Started process (PID=1743) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:40:06.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:40:06.517+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:40:06.516+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:40:06.520+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:40:06.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:40:06.521+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:40:06.556+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.053 seconds
[2024-11-01T22:40:36.740+0000] {processor.py:186} INFO - Started process (PID=1759) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:40:36.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:40:36.742+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:40:36.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:40:36.744+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:40:36.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:40:36.745+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:40:36.765+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:41:06.922+0000] {processor.py:186} INFO - Started process (PID=1775) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:41:06.922+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:41:06.924+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:41:06.924+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:41:06.926+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:41:06.926+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:41:06.927+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:41:06.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:41:37.096+0000] {processor.py:186} INFO - Started process (PID=1791) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:41:37.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:41:37.099+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:41:37.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:41:37.101+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:41:37.100+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:41:37.102+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:41:37.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.037 seconds
[2024-11-01T22:42:07.277+0000] {processor.py:186} INFO - Started process (PID=1807) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:42:07.278+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:42:07.280+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:42:07.280+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:42:07.282+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:42:07.281+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:42:07.282+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:42:07.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:42:37.468+0000] {processor.py:186} INFO - Started process (PID=1823) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:42:37.469+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:42:37.472+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:42:37.471+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:42:37.475+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:42:37.474+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:42:37.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:42:37.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.046 seconds
[2024-11-01T22:43:07.665+0000] {processor.py:186} INFO - Started process (PID=1840) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:43:07.666+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:43:07.667+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:43:07.667+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:43:07.670+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:43:07.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:43:07.670+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:43:07.698+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.038 seconds
[2024-11-01T22:43:37.855+0000] {processor.py:186} INFO - Started process (PID=1856) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:43:37.856+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:43:37.858+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:43:37.858+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:43:37.861+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:43:37.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:43:37.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:43:37.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.045 seconds
[2024-11-01T22:44:08.057+0000] {processor.py:186} INFO - Started process (PID=1873) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:44:08.058+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:44:08.059+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:44:08.059+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:44:08.062+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:44:08.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:44:08.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:44:08.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.036 seconds
[2024-11-01T22:44:38.247+0000] {processor.py:186} INFO - Started process (PID=1889) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:44:38.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:44:38.249+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:44:38.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:44:38.251+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:44:38.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:44:38.252+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:44:38.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.039 seconds
[2024-11-01T22:45:08.447+0000] {processor.py:186} INFO - Started process (PID=1906) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:45:08.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:45:08.450+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:45:08.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:45:08.452+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:45:08.451+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:45:08.453+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:45:08.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:45:38.618+0000] {processor.py:186} INFO - Started process (PID=1921) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:45:38.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:45:38.621+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:45:38.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:45:38.623+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:45:38.622+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:45:38.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:45:38.644+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:46:08.791+0000] {processor.py:186} INFO - Started process (PID=1937) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:46:08.791+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:46:08.793+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:46:08.793+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:46:08.795+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:46:08.794+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:46:08.796+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:46:08.816+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:46:38.974+0000] {processor.py:186} INFO - Started process (PID=1954) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:46:38.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:46:38.977+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:46:38.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:46:38.979+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:46:38.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:46:38.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:46:38.999+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
[2024-11-01T22:47:09.164+0000] {processor.py:186} INFO - Started process (PID=1971) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:47:09.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:47:09.166+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:47:09.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:47:09.169+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:47:09.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:47:09.169+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:47:09.191+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:47:39.340+0000] {processor.py:186} INFO - Started process (PID=1988) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:47:39.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:47:39.343+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:47:39.342+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:47:39.345+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:47:39.344+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:47:39.345+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:47:39.366+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.031 seconds
[2024-11-01T22:48:09.521+0000] {processor.py:186} INFO - Started process (PID=2005) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:48:09.522+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:48:09.523+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:48:09.523+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:48:09.525+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:48:09.525+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:48:09.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:48:09.546+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.029 seconds
[2024-11-01T22:48:39.709+0000] {processor.py:186} INFO - Started process (PID=2022) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:48:39.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:48:39.713+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:48:39.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:48:39.716+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:48:39.715+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:48:39.719+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:48:39.738+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.036 seconds
[2024-11-01T22:49:09.901+0000] {processor.py:186} INFO - Started process (PID=2038) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:49:09.902+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:49:09.904+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:49:09.904+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:49:09.906+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:49:09.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:49:09.906+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:49:09.946+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.049 seconds
[2024-11-01T22:49:40.095+0000] {processor.py:186} INFO - Started process (PID=2055) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:49:40.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:49:40.100+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:49:40.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:49:40.103+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:49:40.102+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:49:40.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:49:40.135+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.046 seconds
[2024-11-01T22:50:10.302+0000] {processor.py:186} INFO - Started process (PID=2071) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:50:10.303+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:50:10.306+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:50:10.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:50:10.309+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:50:10.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:50:10.310+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:50:10.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.044 seconds
[2024-11-01T22:50:40.484+0000] {processor.py:186} INFO - Started process (PID=2088) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:50:40.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:50:40.487+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:50:40.487+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:50:40.489+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:50:40.488+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:50:40.489+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:50:40.511+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.032 seconds
[2024-11-01T22:51:10.656+0000] {processor.py:186} INFO - Started process (PID=2103) to work on /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:51:10.657+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_dag_with_python.py for tasks to queue
[2024-11-01T22:51:10.659+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:51:10.659+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:51:10.661+0000] {logging_mixin.py:190} INFO - [2024-11-01T22:51:10.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_dag_with_python.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 1059, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_dag_with_python.py", line 1
    import airflow import DAG
                   ^^^^^^
SyntaxError: invalid syntax
[2024-11-01T22:51:10.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_dag_with_python.py
[2024-11-01T22:51:10.681+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_dag_with_python.py took 0.030 seconds
